Repository ProctorU/hootstrap, pull requests merged in 2018-12, with the labels that each got.

#47 Add support for collapse for navbars
  assets/javascripts/hootstrap.js
  assets/javascripts/hootstrap/collapse.js
Labels: Type: Feature

#50 Import changes from 4.0..4.1.3
  CHANGELOG.md
  Gemfile.lock
  assets/stylesheets/hootstrap/base/_variables.scss
  hootstrap.gemspec
  lib/hootstrap/version.rb
Labels: Type: Feature

#58 Increase $gray-600 contrast against white
  CHANGELOG.md
  Gemfile.lock
  assets/stylesheets/hootstrap/base/_variables.scss
  lib/hootstrap/version.rb
Labels: Status: Reviewed, Type: Feature

#59 Update Hootstrap authors
  CHANGELOG.md
  Gemfile.lock
  hootstrap.gemspec
  lib/hootstrap/version.rb
Labels: Status: Reviewed, Type: Technical Debt
